### ISSUE TITLE
Using Jet/Turbo/Rocket make you perceive it as night.

### ISSUE THREAD

**Issue by ProfessorPopoff** [Mojave-Sun/mojave-sun-13#1388]
Weirdest bug I think i've seen in a while. It goes full night mode the second you get a buzz. Lights work perfectly- You just think it's night.

...Feature?

**Comment by ProfessorPopoff** [comment]
Update: so does getting hit by lasers apparently. If not all, at the very least the eyebot lasers

**Comment by AndrewL97** [comment]
Issue with sunlight layering (I assume). I'll have a look
