### ISSUE TITLE
Crafting element is broken!

### ISSUE THREAD

**Issue by ProfessorPopoff** [Mojave-Sun/mojave-sun-13#1925]
As the title says, it's nonfunctioning. Set up correctly, according to Scar. 

It will play the sound, but spit out an error on the do_after_interactive proc `/obj/item/ms13/component/cell/var/do_afters`

`[19:18:38] Runtime in interactive.dm, line 16: undefined variable /obj/item/ms13/component/cell/var/do_afters
proc name: do after interactive (/proc/do_after_interactive)
usr: ProfessorPopoff/(Max Hegarty)
usr.loc: (wasteland (146,122,3))
src: null
call stack:
do after interactive(the fusion cell (/obj/item/ms13/component/cell), 100, the light bulb (/obj/item/light/ms13/bulb), 0, 1, null, the light bulb (/obj/item/light/ms13/bulb), 1, 10, "mojave/sound/ms13effects/craft...", /obj/effect/hallucination/simp... (/obj/effect/hallucination/simple/progress_focus/skillcheck))
the light bulb (/obj/item/light/ms13/bulb): StartCraftingAtom(Max Hegarty (/mob/living/carbon/human), the fusion cell (/obj/item/ms13/component/cell), /list (/list))
the light bulb (/obj/item/light/ms13/bulb): craft recipes(the fusion cell (/obj/item/ms13/component/cell), Max Hegarty (/mob/living/carbon/human), /list (/list), null)
the light bulb (/obj/item/light/ms13/bulb): craft(Max Hegarty (/mob/living/carbon/human), the fusion cell (/obj/item/ms13/component/cell))
the fusion cell (/obj/item/ms13/component/cell): melee attack chain(Max Hegarty (/mob/living/carbon/human), the light bulb (/obj/item/light/ms13/bulb), "icon-x=16;icon-y=18;left=1;scr...")
Max Hegarty (/mob/living/carbon/human): ClickOn(the light bulb (/obj/item/light/ms13/bulb), "icon-x=16;icon-y=18;left=1;scr...")
the light bulb (/obj/item/light/ms13/bulb): Click(the sidewalk (146,121,3) (/turf/open/floor/plating/ms13/ground/sidewalk), "mapwindow.map", "icon-x=16;icon-y=18;left=1;scr...")
ProfessorPopoff (/client): Click(the light bulb (/obj/item/light/ms13/bulb), the sidewalk (146,121,3) (/turf/open/floor/plating/ms13/ground/sidewalk), "mapwindow.map", "icon-x=16;icon-y=18;left=1;scr...")`

**Comment by Hekzder** [comment]
Fixed by #1974
