### ISSUE TITLE
Radios are quite bugged

### ISSUE THREAD

**Issue by Hekzder** [Mojave-Sun/mojave-sun-13#2064]
I wish I could offer more in depth details, but radios will seemingly cease to work at random points in a round for random reasons and the radios affected are fairly random. 

Examples include the BoS being unable to contact the person inside the gatehouse on the radio from _literally_ right outside the gatehouse. The NCR LT being unable to contact their away team or radiomen. Messages seemingly just get sent into the void and then everyone is left confused and frustrated because they think they're being ignored or that everyone else is dead. 

Telecomms _may_ be a reason/cause for this, and having an actually properly set up telecomms would probably do us good. Otherwise I'm not really sure where to begin with fixing this as the issue itself is hard to fully understand. 

It's worth pointing out this bug has been present since **at least** our first closed Alpha Test, so basically like 5-6 months. Which means the most recent TG radio refactor is not, at least directly, the cause for the buggy behavior most likely.

**Comment by bardinatavern4** [comment]
I'd guess related to telecomms. It could be the radiostatic changes so what I'd suggest is we temporarily revert radiostatic code during a test and see if that fixes anything.

**Comment by Hekzder** [comment]
help wanted

**Comment by ProfessorPopoff** [comment]
Z to Z communication fixed long ago. Only issue now is radios being hearable only if not stored.
