### ISSUE TITLE
You can walk through this specific guard rail

### ISSUE THREAD

**Issue by MinimionBlack** [Mojave-Sun/mojave-sun-13#2192]
## Reproduction: Go to this specific guard rail and walk through it

https://user-images.githubusercontent.com/64515867/196312365-c5950896-c754-4a52-b6d1-ae4a56df5dc9.mp4

**Comment by ProfessorPopoff** [comment]
Yeah I'm in the process of looking into this currently. A recent change messed up some stuff but it'll be easy to fix.

**Comment by Hekzder** [comment]
Resolved by #2193
