### ISSUE TITLE
Bullets can Fill Space with Nothing inside Storage

### ISSUE THREAD

**Issue by Taylorkills2** [Mojave-Sun/mojave-sun-13#2202]
## Reproduction:
Grab a single bullet, place it into backpack. Grab another single bullet so it's in-hand.
Create a stack by using the in-hand bullet on the single bullet in the backpack.
You now have a stack of 2 bullets in-hand, and a Filled Empty space in the backpack where the bullet was.
You cannot put anything on the empty space, but you can fix this by splitting the bullet stack back up.

**Comment by ChungusGamer666** [comment]
this should be resolved as i made it so you can't stack bullets in backpacks
@ProfessorPopoff
