### ISSUE TITLE
Suggestion: New Raider role Cook(Honorary Cook-Cook)

### ISSUE THREAD

**Issue by Taylorkills2** [Mojave-Sun/mojave-sun-13#2211]
A raider role specifically for gathering/cooking food.

It's actually pretty hard getting random raiders to go out and gather/cook food so it'd be nice to have a Raider role specifically for it.
Maybe even give them a Flamer like weapon when those come.

**Comment by ProfessorPopoff** [comment]
It doesn't seem like there's really all that much of a reason to have this. You can already self-designate a raider as your little cook fella if you want to.

And I don't think we have any intentions of casually giving anyone a flamethrower right now.

**Comment by Taylorkills2** [comment]
Flamer thing is more of a flavor thing, not give a Raider role super OP weapon. 

And you ignore what I said about it being hard to get a raider to gather and cook food. You can designate someone as a cook, but it's more likely they'll run off and never return before they make a serious effort.

With a role it creates the obligation on the player's part that they're supposed to make some food between doing normal raiding thing, rather than being singled out randomly by another to do something they have no interest in and no intention when they joined the round.

**Comment by QuartzMech** [comment]
I've been playing raider as cook for a few tests now, and it really doesn't need its own role. You can just grab one of the cleavers from the main table roundstart and start cooking things. I've never seen anybody end up the designated chef who didn't want to be.

**Comment by ProfessorPopoff** [comment]
Overall just doesn't seem necessary. We're careful about adding extra roles, and roles that are added have to be meaningful. Anyone in the raiders can designate themselves as whatever they want. It's not a very uptight faction.
