### ISSUE TITLE
Church has pews with more than one pew furniture item per tile

### ISSUE THREAD

**Issue by conk444** [Mojave-Sun/mojave-sun-13#2263]
## Round ID:
[63](https://scrubby.melonmesa.com/round/63)

## Testmerges:

[#2262: 'Disable respawn timer (do not merge)' by Koshenko at commit 283b48b1c3](https://www.github.com/tgstation/tgstation/pull/2262)

## Reproduction:
1. Enter church
2. Examine pews
3. Certain tiles will have two pews instead of the recommended one pew

**Comment by ProfessorPopoff** [comment]
According to the map editor, this isn't true. This church?
![image](https://user-images.githubusercontent.com/51188571/215292567-bd274a9f-5bca-4798-805a-f6e9d3e07c0b.png)

**Comment by TheRealScarHomie** [comment]
bot pr

**Comment by conk444** [comment]
> According to the map editor, this isn't true. This church? ![image](https://user-images.githubusercontent.com/51188571/215292567-bd274a9f-5bca-4798-805a-f6e9d3e07c0b.png)

There's a different church somewhere near there not that church the pews are facing down in the church I'm talking about sorry I'm new to this server I don't know the names of the buildings

**Comment by ProfessorPopoff** [comment]
I see them.

It's a basketball court. Thanks for the heads up, it'll get fixed.
![image](https://user-images.githubusercontent.com/51188571/215303662-205eff96-a2f3-4cf2-8e59-7af422e8056f.png)
![7619ac2c57a94c8c67534e85a62d6314](https://user-images.githubusercontent.com/51188571/215303672-54832f01-89ac-40b9-a497-95b3afa486ac.jpg)

**Comment by ProfessorPopoff** [comment]
Will be fixed in upcoming PR.
