### ISSUE TITLE
Pop up windows not working on BYOND 515.1621

### ISSUE THREAD

**Issue by Joel-682** [Mojave-Sun/mojave-sun-13#2484]
Reporting client version: 514.1589

## Round ID:
[251](https://scrubby.melonmesa.com/round/251)

## Testmerges:
- [DNM: Tgchat fixes](https://github.com/Mojave-Sun/mojave-sun-13/pull/2467)
- [DNM - testing issue with compile options](https://github.com/Mojave-Sun/mojave-sun-13/pull/2459)
- [Hellpig but enhanced](https://github.com/Mojave-Sun/mojave-sun-13/pull/2273)
- [THE HIGHWAYMEN](https://github.com/Mojave-Sun/mojave-sun-13/pull/2481)
- [unticks station traits!!](https://github.com/Mojave-Sun/mojave-sun-13/pull/2482)
- [LOOK AROUND SYSTEM (TEST THING)](https://github.com/Mojave-Sun/mojave-sun-13/pull/2483)

## Reproduction:

1. Download and install BYOND 515.1621 at https://www.byond.com/download/
2. Launch Mojave Sun
3. Click the "Character Setup" Button
4. Ta-da! An empty white window will appear (Normal), but then instead of loading into the character setup, it will dissapear.

-I believe the BYOND version is to blame because I reinstalled 514.1589, ran it with that, and it works fine.

**Comment by ProfessorPopoff** [comment]
Don't update to newer versions of BYOND unless you have to. It's **constantly** breaking things. Nothing that we are willing to personally do about it at the time.

514.1583 is recommended, you can download it from here: https://www.byond.com/download/build/514/
