### ISSUE TITLE
Examine text for gas masks is broken.

### ISSUE THREAD

**Issue by phoenixdev0117** [Mojave-Sun/mojave-sun-13#2525]
## Testmerges:

#2482 
#2459 

## Reproduction:
![image](https://github.com/Mojave-Sun/mojave-sun-13/assets/55408180/39a3c2ca-c850-4cd9-bfa0-6dc41020e91d)

Whenever a gas mask is examined, at least by a ghost, they return no text. If it is examined again, one gets the "You examine the gas mask closer, but find nothing of interest"

Steps for reproduction:
1. In the map MiniMammoth, observe.
2. Go to the irradiated vault (Photo here 
![image](https://github.com/Mojave-Sun/mojave-sun-13/assets/55408180/412ae553-a8a9-4af0-8cbc-70bf313e9c39)
)
3. Examine the gas mask above the skeleton. You won't see anything.
4. Examine it again to get the "You examine the gas mask closer, but find nothing of interest" message

**Comment by Joel-682** [comment]
So, it's not just /obj/item/clothing/mask/gas/ms13/modern, but every mask with "/obj/item/clothing/mask/gas/ms13". Masks from the base game (/obj/item/clothing/mask/gas) have their examine work. I presume this may have something to do with the traits of /obj/item/clothing/mask/gas/ms13.

**Comment by Joel-682** [comment]
After playing a bit with the variables in /obj/item/clothing/mask/gas/ms13, I believe that it isn't a problem. Despite letting it inherit all the variables from /obj/item/clothing/mask/gas, the examine still doesn't work. 

I love code, someone smarter than me fix this. I think the examine verb may be broken in regards to gas masks?

**Comment by ProfessorPopoff** [comment]
I know what's causing the issue- I cut it off and forgot about it. I'll have it fixed and filled out.

**Comment by AndrewL97** [comment]
LEAVE THE ROTTING CARCASS ALONE
