### ISSUE TITLE
Using crowbar on /obj/structure/closet/crate/ms13/woodcrate crashes the game

### ISSUE THREAD

**Issue by ghost** [Mojave-Sun/mojave-sun-13#300]
The title says it all.
![화면 캡처 2021-08-21 161907](https://user-images.githubusercontent.com/58895726/130314151-9f9015af-cb0f-4804-9b0e-6f3a849d4337.png)

**Comment by ProfessorPopoff** [comment]
Doesn't crash me when I attempted to replicate it

**Comment by Hekzder** [comment]
Doesn't seem to really be an issue throughout all of testing so far.
