### ISSUE TITLE
Ghosts jitter uncontrollably if you orbit once

### ISSUE THREAD

**Issue by Imaginos16** [Mojave-Sun/mojave-sun-13#403]
## Reproduction:
Step 1: Be a ghost
Step 2: Click on anything that makes the ghost orbit
Step 3: ???
Step 4: Congratulations, now your ghost permanently has a seizure!
![image](https://user-images.githubusercontent.com/77556824/131235786-c2b2cf48-de01-4279-a520-4a44e63f0d01.png)

**Comment by Imaginos16** [comment]
Addendum: Might make a separate issue for it, but it seems orbiting a jittery ghost crashes you.

**Comment by dragomagol** [comment]
> 
> 
> Addendum: Might make a separate issue for it, but it seems orbiting a jittery ghost crashes you.

That was me trying to orbit the ghost, I crashed and was unable to re-join.

**Comment by Hekzder** [comment]
Fairly certain this has been resolved either by recent BYOND or TG updates. Haven't been able to reproduce recently or heard any problems with it during recent tests.
