### ISSUE TITLE
No storage icon for melee on belt, possibly on back too

### ISSUE THREAD

**Issue by Hekzder** [Mojave-Sun/mojave-sun-13#411]
Once again basically title. Melee weapons shart out because they try to search for a non-existent belt slot storage sprite. Potentially also applies to back and suit slot. 

Not even sure we have sprites for these. If we don't have them by closed beta testing we should just boof the melee trying to search for storage entirely.

## Reproduction:

Spawn melee weapon, put it on your belt. Observe GMod checkerboard error texture.

**Comment by ProfessorPopoff** [comment]
Got for any of the three storage spots, back/belt/suit storage

**Comment by Hekzder** [comment]
Placeholder fix implemented in #661, basically not an issue anymore. But when we get worn sprites we'll slap them on.
