### ISSUE TITLE
Strong explosions can still make space tiles

### ISSUE THREAD

**Issue by ProfessorPopoff** [Mojave-Sun/mojave-sun-13#472]
Tried to fix by altering base turfs a while ago, still isn't fixed. 
![image](https://user-images.githubusercontent.com/51188571/131787308-929626e2-7ee8-40dd-8313-69c1a416d69a.png)

**Comment by ProfessorPopoff** [comment]
I'm 100% sure this was because our turf paths were updated and the json file baseturf wasn't corrected. I changed it at some point up the road, so it's likely fixed.

**Comment by Hekzder** [comment]
Epic swag nae nae gaming fortnite
