### ISSUE TITLE
Explosions don't function correctly on /turf/open/floor/plating subtypes

### ISSUE THREAD

**Issue by ProfessorPopoff** [Mojave-Sun/mojave-sun-13#889]
As said in the title. They flat out don't work at all, hardly. To emphasize how bad it is, dropping maxcaps outside does nothing,

https://gyazo.com/08e393bfc779621e0a0ed0550035d3e8
https://gyazo.com/197e77e9022449beea687d65c6865051

**Comment by AndrewL97** [comment]
Not sure if this was before or after sunlight, but it also looks like there is a weird lighting issue in that second video
There might be some weird area setting causing this - I know that we had some configuration to make the combat tests work.
I'll have a look

**Comment by ProfessorPopoff** [comment]
> Not sure if this was before or after sunlight, but it also looks like there is a weird lighting issue in that second video There might be some weird area setting causing this - I know that we had some configuration to make the combat tests work. I'll have a look

I already checked it. It has nothing to do with area. It is STRICTLY turf based issue from what I looked at. This is pre-lighting. Ignore lighting.

**Comment by AndrewL97** [comment]
@ProfessorPopoff can you please confirm fixed when you're free xo

**Comment by Hekzder** [comment]
Fixed by #1858, thanks Gomble xoxoxoxoxo
